USE test;
DECLARE @PARENT_ID INT;
DECLARE @COUNTER INT;
DECLARE @COUNT_TOTAL INT;
DECLARE @MIN INT;
DECLARE @CURSOR CURSOR;
SET @CURSOR = CURSOR SCROLL
FOR SELECT parent_id, COUNT(*) 
    FROM example GROUP BY parent_id ;

OPEN @CURSOR;
   FETCH NEXT FROM @CURSOR INTO @PARENT_ID, @COUNT_TOTAL
	WHILE @@FETCH_STATUS = 0
	BEGIN
	        --SELECT @COUNT_TOTAL
			WHILE (@COUNT_TOTAL > 3)
			BEGIN
			SET @MIN = (SELECT MIN(count_pid) from example WHERE parent_id = @PARENT_ID);
			DELETE FROM example WHERE parent_id = @PARENT_ID AND count_pid = @MIN;
			SET @COUNT_TOTAL = @COUNT_TOTAL - 1;
			END 

      FETCH NEXT FROM @CURSOR INTO @PARENT_ID, @COUNT_TOTAL
    END
CLOSE @CURSOR
DEALLOCATE @CURSOR